### ISSUE TITLE
Enter phenology field data

### ISSUE THREAD

**Issue by jnatali** [jnatali/sagehen_meadows#10]
# Overview
We need to digitize phenology measurements taken in the field at Sagehen phenocam sites. We will correlate some of these observations (e.g. leaf length) with vegetation greenness from the phenocams. And we'll use other observations to describe differences between vegetation patches through the seasons.

## Task
Enter data from written and audio files into a [shared spreadsheet](https://docs.google.com/spreadsheets/d/1uNq-oA5pPxfIj03lnW0eRrE-ArUc9dWq-DELhp1t-1Q/edit?gid=1143433475#gid=1143433475).  On the sheet, there are columns for general measurement of percent cover, then columns for specific plant types: `sedge`, `willow` and `mixed herbaceous`. On the bottom of the sheet, choose the tab for the appropriate year (2019-2025).  There's also a tab "Phenocam ID Key" that lists the phenocam name, describes its locations and lists associated wells. In audio files, I try to describe the location in case I misname the well.

### Data Input Assignment and Task
Please stick with your year assignment so you're working on your own tab in the shared spreadsheet. That should help avoid data overwrites or doubled entries.
- June: 2025 data
- Ryan: 2024 data

#### Task 1 Checklist Check-up

Before we add more data to the sheets, let's check on what's already completed. We have a checklist below, is it correct and up-to-date? 

For your year (2024 or 2025), reconcile the checklist with the spreadsheet data. On the checklist, are the entries complete for the dates checked? And from the spreadsheet, are there dates where data is entered (and complete) and should be checked on the checklist?  

How to know what's complete? For each observation period (might be spread over a 2-3 day period), we should have data for sites East 1-4 with all three plant types represented at each site; at Kiln, we should have data for sites Kiln 1-3, 5-6 in 2025 and then also Kiln-4 in 2024. Some Kiln sites have no willow and some are only willow. See the "Phenocam ID Key" sheet for details on plant types at Kiln sites. 

How to account for completed or missing data? If all is complete, check the checkmark in the checklist below. If there's already a check but missing data, compile a list of missing data for any observation periods and add as a  comment at the bottom of this issue. You can track missing data however is easy for you, I want an easy-to-understand list. It might be: checked observation dates with missing data (list what's missing), unchecked observation dates with some data (list what's missing). And if someone entered data and it's complete, but forgot to check the checkmark...please check it! 

#### Task 2 Data Entry

From the phenology observation checklist below, start with an unchecked observation and open its source data file. There should be linked files available for 2024-25. I recommend starting with the .pdf "cheatsheets" since they're written down and well organized.  My audio files will likely be more challenging to follow. There's cursing and possibly muttering and rambling or long pauses, please forgive me! For most part, I tried to follow the data entry form organization, so it might help to look at an example pdf (linked from the checklist). In the past, I've used an a tool called 'Whisper Transcription' to help translate audio to text. It's far from perfect, even with numbers. Don't trust it completely! You need to listen, but the tool can help you see the text and skip around the file to repeat or ignore section (like where I'm rambling about plant identification and their crunchiness!?).

Once you pick a date and file, please try to complete *all* data entry for that date. It doesn't have to be done all at one time, but just stick with that date (each time you sit down to work) until it's done rather than jumping around. Once you've completed data entry for the date, check it off below so we can keep track.

Each "plant type" will have its own row for an entry. MH and Sedge will have % cover, but willow will not. 

The last column in the sheet should be a catch-all for any notes.

If there's a question about some data or info and where to put it, you can add note in the spreadsheet and "at" me in a comment directly in the sheet. If there's a file I should reference, linking it in the comment could help. If it's not fitting in the sheet, then you can comment below (in this issue, again "at" me) with more description and I can take a look. Again, a link to the source file could help.

**Note:** we're using github to track this task (as an "issue"), but the files are all just on Google Drive. Use the links provided here and that should be enough. There's no need to "check in" or "pull" code or data.

#### Highest priority data:
- correct date, time (if noted) and phenocam id
- leaf length (always enter in cm) for willow and sedge
- percent cover for sedge
- percent cover for mixed herbaceous

#### Should be consistent, so possibly useful:
- herbivory for willows
- gall and rust presence for willows, less important but could be useful

#### Challenging and not critical, so SKIP THIS FOR NOW.
- list of plants for mixed herbaceous could be useful, but it's not critical right now for the paper. Ideally, plants will be listed as a 6-character code, e.g. DESCES. Sometimes the plant is only identified to genus (not species) so it'll be a 3-character code e.g. CAR for Carex (a sedge), or POA for a type of grass. Write whatever it says. I will try to translate it into the plant abbreviations. If helpful see our [shared list of plant abbreviations](https://docs.google.com/spreadsheets/d/1zYU1PKwvjwCjZ30u8tqqQfBAHrr5w2lRdm4nUS3dhLk?usp=drive_fs).
- presence of grasshopper, we might consider future data collection so we can correlate with soil moisture, percent cover and LAI but we weren't consistent and systematic.

#### 2018 Pheno Observations: Data Entry Dates and Files
- [ ] 07/25 in Orange Vol II pp 29-33, Black p23
- [ ] 08/10 in Black p 34-35
- [ ] 08/26 in Orange Vol II pp 40-56, plant list Black p 39
- [ ] 09/16 Black p 41
- [ ] 10/15 Black p 45-48
- [ ] 11/18 Black p 49-51

#### 2019 Pheno Observations: Data Entry Dates and Files
- [ ] 06/02 Black pp 52-55
- [ ] 06/17 Black pp 56-61
- [ ] 07/05 (only some so far) in Orange Vol II pp 75-81
- [ ] 07/26 (only some so far) in Orange Vol II p 84-96
- [ ] 08/20 in Orange Vol II, p 117 and 112-114, 107-109
- [ ] 09/21 (missing East 2, 3, Kiln 1) in Orange Vol II, p 121 and 113
- [ ] 10/05 in Orange Vol II, p 129
- [ ] 10/19 (missing East 1, 3, Kiln 1) in Orange Vol II
- [ ] 11/03 in Yellow Vol I p3

#### 2021 Pheno Observations: Data Entry Dates and Files
- [x] 05/18 in Yellow Vol I pp 25-32
- [x] 06/05-06/07 in Yellow Vol I pp 40-45, 48
- [x] 06/19-06/20 in Yellow Vol I p 63
- [ ] 07/03 in Yellow Vol I pp 64-76
- [ ] 07/16 in Yellow Vol I p 79, 81-91
- [ ] 08/05 in Yellow Vol I pp 92-99
- [ ] 08/21 in Yellow Vol I pp 100-103, 105-108
- [ ] 09/08 (audio [folder of mp3s](https://drive.google.com/open?id=14575BlCkBgYiRvfKkPBk1S2x0G8z_JZs&usp=drive_fs))
- [ ] 09/23 (audio [folder of mp3s](https://drive.google.com/open?id=1SO3CUJlrOlAx2noPpxJvEJ47kXMKdq4z&usp=drive_fs))
- [ ] 10/05 (audio [folder of mp3s](https://drive.google.com/open?id=17aTrLDuJc0tja7OxYQur8DQSTapeGevL&usp=drive_fs))
- [ ] 11/12 (audio [folder of mp3s](https://drive.google.com/open?id=1BfDAEr5ExXYKxCzNUeNUsSZWNY9Er7nR&usp=drive_fs))

#### 2024 Data Entry Dates and Files
- [x] 06/01-06/02 (audio [folder of mp3s](https://drive.google.com/open?id=1ARcV7y3zk8lTuQEFBWAiJwtMpH2KlMOk&usp=drive_fs))
- [x] 06/15 (missing Kiln) in Yellow Vol I pp 133-134, 138-144
- [x] 06/29 in Yellow Vol I pp 147-151
- [x] 07/12-07/14 ([pdf](https://drive.google.com/open?id=1rAWLIVuzmGgfA_fuK8bm9cJ4twRhTWo_&usp=drive_fs))
- [ ] 07/27 (audio [folder of mp3s](https://drive.google.com/open?id=1vPw4WeRBARK6pgxwu9b19UOkfFG_OOmE&usp=drive_fs))
- [x] 08/10 ([pdf](https://drive.google.com/open?id=1rAWLIVuzmGgfA_fuK8bm9cJ4twRhTWo_&usp=drive_fs))
- [ ] 09/06 (audio [folder of mp3s](https://drive.google.com/open?id=1PFYGXabuw5tAkiFw5jkdNGfgkQQpSUHd&usp=drive_fs))
- [ ] 09/20-09/21 (audio [folder of mp3s](https://drive.google.com/open?id=1mxNDj0jdHe2oIDS24LoJZ4Xh8kPRvIhE&usp=drive_fs))
- [x] 10/05-10/06  
- [ ] 10/21 (audio [folder of mp3s](https://drive.google.com/open?id=12h15IGxnC_CaZpxq0Btn4arvvpbtHTmq&usp=drive_fs))
- [ ] 11/09 (audio [mp3](https://drive.google.com/open?id=1-Kb0VKFBn-AkcoMxHC5NQxUGXWKT_hWx&usp=drive_fs))

#### 2025 Pheno Observations: Data Entry Dates and Files
- [x] 05/25-05/28 ([pdf](https://drive.google.com/open?id=1XZFrkOCcZ7p5je4fjznQjNpMFcQNiOtn&usp=drive_fs), some of Kiln3 entered)
- [x] 07/11-07/14 ([pdf](https://drive.google.com/open?id=1XZFrkOCcZ7p5je4fjznQjNpMFcQNiOtn&usp=drive_fs))
- [x] 07/27 ([pdf](https://drive.google.com/open?id=1XZFrkOCcZ7p5je4fjznQjNpMFcQNiOtn&usp=drive_fs))
- [ ] 07/27 (audio [folder of mp3s](https://drive.google.com/open?id=1RYMeE9iLYb_kfBc1QgHw6CK8QBG45d1N&usp=drive_fs))
- [ ] 08/09 (audio [folder of mp3s](https://drive.google.com/open?id=1F-7Fy8ZnHW_Ddwqxhr0l0M9sCSCHc0WP&usp=drive_fs))
- [ ] 08/10 (audio [mp3](https://drive.google.com/open?id=1i8r1h9aH2xoK3_4LTRxNPJjWbQqloFhD&usp=drive_fs))
- [x] 08/22-08/23 ([pdf](https://drive.google.com/open?id=1XZFrkOCcZ7p5je4fjznQjNpMFcQNiOtn&usp=drive_fs))
- [ ] 09/03 (audio [folder of mp3s](https://drive.google.com/open?id=1ayRQrL8-BtH1zN7BaObtvAhnd21d1QEV&usp=drive_fs))
- [ ] 09/04 (audio [mp3](https://drive.google.com/open?id=1x6U3JuyDqx6gQA-kTZ-qUmorqkeTcJ66&usp=drive_fs))
- [ ] 10/20 (audio [mp3](https://drive.google.com/open?id=1lyk4Ahf1W6aUhkVbv3XdpSBSTyMkUsRL&usp=drive_fs))

## Resources
- [Data Entry Spreadsheet](https://docs.google.com/spreadsheets/d/1uNq-oA5pPxfIj03lnW0eRrE-ArUc9dWq-DELhp1t-1Q/edit?gid=1143433475#gid=1143433475)
- [Plant Names and Abbreviations](https://docs.google.com/spreadsheets/d/1zYU1PKwvjwCjZ30u8tqqQfBAHrr5w2lRdm4nUS3dhLk?usp=drive_fs)

**Comment by KaraSmit** [comment]
<img width="484" height="217" alt="Image" src="https://github.com/user-attachments/assets/1ca86ee8-b4e0-4785-8d1d-b9d73bf95931" />

Hi Jen,
Page 4, camera LO-2 of 07/12-07/14 pdf mixed herb percent cover category doesn't add up to 100%. What should I put?

**Comment by KaraSmit** [comment]
<img width="441" height="55" alt="Image" src="https://github.com/user-attachments/assets/cc803a61-755b-4bc6-8ef0-74a05be12154" />

@jnatali Also, there are 3 kinds of POA. What should I put if the entry just says POA

**Comment by KaraSmit** [comment]
@jnatali similar with 'jun'

<img width="585" height="132" alt="Image" src="https://github.com/user-attachments/assets/39f326ad-ce3a-4204-a2d1-9b8028101c30" />

**Comment by jnatali** [comment]
@KaraSmit, For Poa (POA) and Juncus (JUN), just keep a three-letter abbreviation. I can't differentiate the species. Thanks for checking!

**Comment by jnatali** [comment]
> <img alt="Image" width="484" height="217" src="https://private-user-images.githubusercontent.com/173848086/556647251-1ca86ee8-b4e0-4785-8d1d-b9d73bf95931.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzI0MDg1NTQsIm5iZiI6MTc3MjQwODI1NCwicGF0aCI6Ii8xNzM4NDgwODYvNTU2NjQ3MjUxLTFjYTg2ZWU4LWI0ZTAtNDc4NS04ZDFkLWI5ZDczYmY5NTkzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMwMVQyMzM3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWE3ZTYwNTUzNDBlMjE5NmIxMDI2NTgxMDM0ZTIxMzRiNGE3Y2MwMTM0Zjc2Nzk4ZmZjMmY0ZjRkMTVhZjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.piVDAB13DQEaW23USch1Y0KAi1lax7B8l5tNQ0NtmPM">
> Hi Jen, Page 4, camera LO-2 of 07/12-07/14 pdf mixed herb percent cover category doesn't add up to 100%. What should I put?

@karasmit, Thanks for the screenshot! Trust the 75%. Increase MH to 23%

**Comment by KaraSmit** [comment]
Hey @jnatali, I just want to verify that we're not including anything for percent cover of willows? There are many entries in the sheets for willow percent green and percent cover, but these entries aren't consistent throughout. I notice there is columns in the sheet for Willow:

-  **Willow Leaf Cover (% or class)** 

-  **Willow Color**. 

I've included a few instances where this appears in the **2024_Saghen_Pheno_Sheets**.

<img width="911" height="377" alt="Image" src="https://github.com/user-attachments/assets/8b7c591c-1934-4bf8-b53b-8d415fa02a22" />

<img width="908" height="359" alt="Image" src="https://github.com/user-attachments/assets/11f2bcab-7c74-402a-8dc9-5e409f1c0ec1" />

<img width="913" height="361" alt="Image" src="https://github.com/user-attachments/assets/0d3cf156-54c9-4787-8c81-b4b72b897a35" />

**Comment by jnatali** [comment]
@KaraSmit, good question about willow cover %age and color. Thanks for sharing examples. Tagging @wendyfeng04 here in case the info's helpful. 

As you say, we have columns for willow leaf cover and color. And the data is not consistently documented. It's probably because I only start paying attention to % cover and color once the leaves start falling and/or turning yellow. So most of the summer, everything's green and full, but at some point in August, I start noticing signs of senescence and/or stress.

So if you see potentially applicable data for those columns, please add!!

To go through the screenshot examples:
- 08/10/2024 Kiln 3 Willow, you could leave "Willow Leaf Cover" blank (no %ages) but I'd recommend inserting "some outer branches dead to 0.8-1.2 m" since dead branches have no leaves. I'm documenting this to help verify the photos from the cameras. I have to outline a "region of interest" and I'll likely leave out the lower branches and it'd help to have confirm that they're actually dead.  For "Willow Color" I'd enter: "99% green leaves, v. few yellow on outer edges" (but without the quotes!)
- 08/10/2024 U2 Willow, for "Leaf Cover" I'd enter: "very full, 4-5m tall; few bare red branches ~1m; few dead branches in middle". For "Color" I'd enter: "95% green; one branch section 35% green"
- 08/10/2024 E3 Willow, for "Leaf Cover" I'd enter: "90% full; few lo and up branch dead" and for "Color": "99% green"

Can see how this is tough to interpret, hope my explanations help!


> Hey [@jnatali](https://github.com/jnatali), I just want to verify that we're not including anything for percent cover of willows? There are many entries in the sheets for willow percent green and percent cover, but these entries aren't consistent throughout. I notice there is columns in the sheet for Willow:
> 
> * **Willow Leaf Cover (% or class)**
> * **Willow Color**.
> 
> I've included a few instances where this appears in the **2024_Saghen_Pheno_Sheets**.

**Comment by KaraSmit** [comment]
Hey @jnatali 

Just want to verify that I should still enter this data for **2024 Data Entry Dates and Files 06/15 (missing Kiln) in Yellow Vol I pp 133-134, 138-144**

The top of the page says that the data was entered. 

<img width="365" height="481" alt="Image" src="https://github.com/user-attachments/assets/e05aaa6f-5918-49e9-b741-7b6acfb2a90b" />

**Comment by KaraSmit** [comment]
@jnatali another question. This time for **2024 Data Entry Dates and Files 06/29 in Yellow Vol I pp 147-151**

What would I put for the **percent cover** for the sedge category? There appears to be a silt category.

<img width="431" height="258" alt="Image" src="https://github.com/user-attachments/assets/c65eac55-7578-4992-a780-296312175ec6" />

**Comment by jnatali** [comment]
If there's a "bare ground" category, that'd be it. I recall there was silt
deposited from the creek, probably on top of the thatch. Thanks for
catching this, appreciate your care with the data!

**Comment by KaraSmit** [comment]
@jnatali thank you for the quick response! What the **Files 06/15** issue above?

**Comment by jnatali** [comment]
> Hey [@jnatali](https://github.com/jnatali)
> 
> Just want to verify that I should still enter this data for **2024 Data Entry Dates and Files 06/15 (missing Kiln) in Yellow Vol I pp 133-134, 138-144**
> 
> The top of the page says that the data was entered.
> 
> <img alt="Image" width="365" height="481" src="https://private-user-images.githubusercontent.com/173848086/568117999-e05aaa6f-5918-49e9-b741-7b6acfb2a90b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQ2MjkzNTYsIm5iZiI6MTc3NDYyOTA1NiwicGF0aCI6Ii8xNzM4NDgwODYvNTY4MTE3OTk5LWUwNWFhYTZmLTU5MTgtNDllOS1iNzQxLTdiNmFjZmIyYTkwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMyN1QxNjMwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODkwYTRkNjk1YmU4NTY5ZGIyMzhlOGNiMmViOTYyNzczMWVlN2FjYjVmYTZkNjgyZjBjZDdkM2NmMGMxMjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.heGqA596_-Hysmx6BhBcGP13PYQKO6AOKurLZvUzOHg">

Hi @KaraSmit -- just commented in the spreadsheet to confirm we have SOME of the 06/15/2024 data entered, but we're missing all KILN + LO observations + UP-1. Found them -- they're in Yellow Vol I pp138-144. Those still need to be entered!!

**Comment by KaraSmit** [comment]
@Jen , could you review **240726_1642_pheno** in 07/27 (audio [folder of mp3s](https://drive.google.com/open?id=1RYMeE9iLYb_kfBc1QgHw6CK8QBG45d1N&usp=drive_fs)) at minute 5 and let me know what to put for percent cover mixed herbaceous?

**Comment by jnatali** [comment]
@juneguthrie and @rya-n-guyen: Hello! Welcome to the Pheno Field Data issue. I added details to the tasks at the top. Check out the instructions, see if you can complete Task 1 (reconciling the checklist, listing missing data). It might help to try Task 2, just for one date,  but I think it'll be challenging with the audio. I suspect it'll be easier if we can find a time to do one transcription together in person, then maybe even sit on zoom for 30-45 minutes while you work on it so I can pop in to help. Don't sweat Task 2 if it's just too challenging. You are plenty smart -- it's just that you have NO context and I ramble a lot in the audio.

I've also assigned one reading each for next week; see the [slides for our next MeadowRAP meeting](https://docs.google.com/presentation/d/1RfglvJc7WVqSbNLam28Qgjm1venhiW2suwl8lPIjdJ4/edit?slide=id.g39c4a457577_0_0#slide=id.g39c4a457577_0_0) for links in the Agenda. 

Ryan: Allen-Diaz 1991
June: Ramstead et al 2012 (you can also peruse Allen-Diaz for context about Sagehen groundwater)

During our meeting, It'd be great if you could summarize the study and major findings in five minutes with 1-2 slides. Just add slides (placeholder are there). Copy and paste in figures from the paper to help!

Any questions, you can "at" me here. You can see others' comments. I try to be responsive!
